# Generated by Django 5.1.7 on 2025-05-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_choice_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.PositiveIntegerField(default=1, help_text='Score for this question'),
        ),
    ]
